image: Visual Studio 2017

environment:
  nodejs_version: "6"

# build cache to preserve files/folders between builds
cache:
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Build script
build_script:
  - dotnet restore
  - dotnet build -c Release
  - npm run build

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Backend tests
test:
  # assemblies to test
  assemblies:
    - '**\*.Tests.dll'

# Don't build a branch if there's a PR from it.
skip_branch_with_pr: true
